### ISSUE TITLE
typo in the script "prepare-ubuntu-22.04-template.sh"

### ISSUE THREAD

**Issue by dav178** [fabianlee/tf-vsphere-singlevm-from-template#3]
In the script "prepare-ubuntu-22.04-template.sh"

line 38
echo net.ipv6.conf.l0.disable_ipv6=1 | sudo tee -a /etc/sysctl.conf

should be with a "o" instead of a "0" :
echo net.ipv6.conf.lo.disable_ipv6=1 | sudo tee -a /etc/sysctl.conf

If not you have this error when checking the file with sysctl -p

ubuntu$ sudo sysctl -p
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
sysctl: cannot stat /proc/sys/net/ipv6/conf/l0/disable_ipv6: No such file or directory

**Comment by fabianlee** [comment]
thanks, you are correct.  changed and pushed the correction.
